apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: fastapi-app
  template:
    metadata:
      labels: 
        app: fastapi-app
    spec:
      containers:
        - name: fastapi-container
          image: galvesb/fastapi-argocd:latest
          ports:
            - containerPort: 8000